### ISSUE TITLE
About connections 

### ISSUE THREAD

**Issue by TooFast4ya** [DedaDev/discord-arduino-simplest#1]
I run bash I type: node bot.js cause my js file is called that. It runs fine it says, 
**Com 1 connected** 
**Com 3 available** 

But my arduino is on **com 3.** 

And cause of that, after 10s the thing crashes cause It can't connect to the Arduino cause its looking at the other port. I need to be connected to **Com 3** not Com 1 

If you could help me would be appreciated. Thank u

**Comment by DedaDev** [comment]
Have you tried passing the `port` option while initializing the board?
`const board = new five.Board({ port: "COM3" });`

**Comment by TooFast4ya** [comment]
No I will try thank u. Il let u know.

**Comment by TooFast4ya** [comment]
Thanks u so much. It works. 👍
